# Generated by Django 5.2.6 on 2025-09-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dep_mane',
            new_name='dep_name',
        ),
    ]
